# -*- coding: utf-8 -*-
"""comptech_app1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ATXUrRCyrMPGlcZU8quv3mhphaPOoPaJ
"""

import streamlit as st
from parser_r import parser
from interpreter_r import Interpreter
import io
import sys

st.title("R Script-like Interpreter (Simple)")

code = st.text_area(
    "Input R Script Code:",
    value='print("Hello, world!")\ncat("Thanks")',
    height=150
)

if st.button("Run"):
    try:
        old_stdout = sys.stdout
        sys.stdout = buffer = io.StringIO()

        ast = parser.parse(code)
        interpreter = Interpreter()
        interpreter.run(ast)

        sys.stdout = old_stdout
        st.success("Output:")
        st.text(buffer.getvalue())

    except Exception as e:
        st.error(str(e))